import type { Metadata } from "next";
import { Geist, Geist_Mono, Metal_Mania, Rubik, Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Nav/Nav";

const rajdhani = Rajdhani({
  weight: "400",
  variable: "--font-rajdhani",
  subsets: ["latin"],
});

const rubik = Rubik({ 
  weight: "400",
  variable: "--font-rubik",
  subsets: ["latin"],
});

const metalMania = Metal_Mania({
  weight: "400",
  variable: "--font-metalMania",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "serena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rajdhani.variable} ${rubik.variable} ${metalMania.variable} `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
